#!/bin/bash
ln -sf /usr/share/zoneinfo/Turkey /etc/localtime
hwclock --systohc
vim /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
grub-install --recheck /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
passwd
useradd -mg wheel hardal
passwd hardal
echo "artixbox" >> /etc/hostname
sudo vim /etc/sudoers