#!/bin/bash
echo "Please connect to internet before continiue"
echo "5"
sleep 1
echo "4"
sleep 1
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1
echo "Starting...\n"
echo "Plese enter BOOT partition as first partition and ROOT as second."
cfdisk /dev/sda
mkfs.ext4 -L BOOT /dev/sda1
mkfs.ext4 -L ROOT /dev/sda2
mount /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
basestrap /mnt linux linux-firmware base base-devel os-prober vim neofetch git runit elogind-runit grub networkmanager xorg xorg-xinit xorg-server dhcpcd pcmanfm xf-86-video-intel libxft libxinerama
fstabgen -U /mnt >> /mnt/etc/fstab
mv ./installer_2 /mnt
chmod +x /mnt/installer_2
echo 'Please write ./install_2 to run second stage.'
artix-chroot /mnt /bin/bash
